# Generated by Django 3.2.7 on 2021-09-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInquirer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.inquirer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.users')),
            ],
        ),
    ]
